### ISSUE TITLE
Sugestion: Add cloudflare IPs to the documentation

### ISSUE THREAD

**Issue by Shad9w** [fideloper/TrustedProxy#10]
Hello.

I used this package to make IPs display correctly on my website that uses cloudflare.
I posted an array with the IPs, maybe someone else needs them:

``` php

'proxies' => array(
        '199.27.128.0/21',
        '173.245.48.0/20',
        '103.21.244.0/22',
        '103.22.200.0/22',
        '103.31.4.0/22',
        '141.101.64.0/18',
        '108.162.192.0/18',
        '190.93.240.0/20',
        '188.114.96.0/20',
        '197.234.240.0/22',
        '198.41.128.0/17',
        '162.158.0.0/15',
        '104.16.0.0/12',
        '2400:cb00::/32',
        '2606:4700::/32',
        '2803:f800::/32',
        '2405:b500::/32',
        '2405:8100::/32'
    )

```

The IPs can be found at the cloudflare website: https://www.cloudflare.com/ips

Have a nice day!

**Comment by timersys** [comment]
@Shad9w sorry to mess with the ticket, but did you have to change Illuminate\Http\Request::HEADER_CLIENT_IP    => 'X_FORWARDED_FOR' ? with cloudflare header in order to make this work?

Im behind a load balancer and I can't make my sessions work
