### ISSUE TITLE
array_keys() error

### ISSUE THREAD

**Issue by wturrell** [fideloper/TrustedProxy#102]
Hello I've just upgraded an app from 5.4.36 to 5.5 (via Laravel Shift, with PHP 7.1.13 on Homestead vagrant box.)

I'm getting this E_WARNING for `vendor/fideloper/proxy/src/TrustProxies.php:162`, even though to the best of my knowledge I've not configured load balancing etc. at all:

> array_keys() expects parameter 1 to be array, integer given

```
    protected function getTrustedHeaderSet()
    {
        $trustedHeaderNames = $this->getTrustedHeaderNames();
        $headerKeys = array_keys($this->getTrustedHeaderNames());

```

Composer has **fideloper/proxy (3.3.4)** (specified as "~3.3")

I can fix it by simply casting to an array with:

`$headerKeys = array_keys((array) $this->getTrustedHeaderNames());`

Is that adequate? (I know nothing about your package...)

(Thanks)

**Comment by fideloper** [comment]
Hi! Can you show me your `app\Http\Middleware\TrustProxies` file? It sounds to me like Shift updated that incorrectly. You can [grab the default from here for Laravel 5.5](https://github.com/laravel/laravel/blob/master/app/Http/Middleware/TrustProxies.php).

**Comment by wturrell** [comment]
Thanks, that was indeed the reason.  Shift added the file as below, with a single header rather than an array, hence the error message.  I'll mention this to them in case it's a wider problem.

```
<?php

namespace App\Http\Middleware;

use Illuminate\Http\Request;
use Fideloper\Proxy\TrustProxies as Middleware;

class TrustProxies extends Middleware
{
    /**
     * The trusted proxies for this application.
     *
     * @var array
     */
    protected $proxies;

    /**
     * The headers that should be used to detect proxies.
     *
     * @var string
     */
    protected $headers = Request::HEADER_X_FORWARDED_ALL;
}
```

**Comment by fideloper** [comment]
Thanks for pasting that in - the value Shift provided there is valid for
laravel 5.6 but NOT 5.5.

**Comment by GilbertoNeto** [comment]
I'm passing by the same problem. But I've made the same cast -> headerKeys = array_keys((array) $this->getTrustedHeaderNames()); at line 162 from my file vendor/fideloper/proxy/src/TrustProxies.php:162, and it work. What's happen in this class, when I do that?

**Comment by aramirez92** [comment]
You just need run: `composer update` after download git changes when you've migrated using laravel shift.

**Comment by martinhschei** [comment]
I'm getting the same error (Laravel 5.6 on Ubuntu). I have moved from Vagrant to Ubuntu and never experienced this issue with the same code repository using Vagrant.

If i die and dump the result of $this->getTrustedHeaderNames() line 162 in TrustProxies it returns the integer 30.

I tried composer update - no change.

in composer.json: "fideloper/proxy": "~3.3".

suggestions? :)

**Comment by gthuo** [comment]
For those like me who may be on 5.5 and referenced the link provided by @fideloper for the original contents of TrustedProxy file, of course the contents have changed with never versions. This is the original content for a 5.5 file:
<?php
namespace App\Http\Middleware;
use Illuminate\Http\Request;
use Fideloper\Proxy\TrustProxies as Middleware;
class TrustProxies extends Middleware
{
    /**
     * The trusted proxies for this application.
     *
     * @var array
     */
    protected $proxies;
    /**
     * The current proxy header mappings.
     *
     * @var array
     */
    protected $headers = [
        Request::HEADER_FORWARDED => 'FORWARDED',
        Request::HEADER_X_FORWARDED_FOR => 'X_FORWARDED_FOR',
        Request::HEADER_X_FORWARDED_HOST => 'X_FORWARDED_HOST',
        Request::HEADER_X_FORWARDED_PORT => 'X_FORWARDED_PORT',
        Request::HEADER_X_FORWARDED_PROTO => 'X_FORWARDED_PROTO',
    ];
}

> Hi! Can you show me your `app/Http/Middleware/TrustProxies.php` file? It sounds to me like Shift updated that incorrectly.
> 
> You can [grab the default from here for Laravel 5.5](https://github.com/laravel/laravel/blob/master/app/Http/Middleware/TrustProxies.php) which should be fine - it'll set that value as an array like it's expecting.

**Comment by djwave28** [comment]
Installed laravel 5.7.  on PHP 7.2.12
**Error:** array_keys() expects parameter 1 to be array, integer given

```
 "require": {
        "php": "^7.1.3",
        "fideloper/proxy": "^4.0",
        "laravel/framework": "5.7.*",
```

Standard Installed TrustProxies
```
   /**
     * The headers that should be used to detect proxies.
     *
     * @var int
     */
    protected $headers = Request::HEADER_X_FORWARDED_ALL;
```

Went back to using the array again to make it work.

```
     protected $headers = [
        Request::HEADER_FORWARDED => 'FORWARDED',
        Request::HEADER_X_FORWARDED_FOR => 'X_FORWARDED_FOR',
        Request::HEADER_X_FORWARDED_HOST => 'X_FORWARDED_HOST',
        Request::HEADER_X_FORWARDED_PORT => 'X_FORWARDED_PORT',
        Request::HEADER_X_FORWARDED_PROTO => 'X_FORWARDED_PROTO',
    ];
```
What am I missing? Seems all confusing.

**Comment by mutiemule** [comment]
Your answer is a saver @gthuo 

Just format it well

**Comment by VRanjithkumar** [comment]
Make sure fideloper/proxy version is 4.0 for laravel >= 5.5
