### ISSUE TITLE
how to set custom HEADER_X_FORWARD in 4.0

### ISSUE THREAD

**Issue by olivM** [fideloper/TrustedProxy#108]
Hi,

Prior to 4.0, i could do something like this in config/trustproxy.php :

    'headers' => [
        (defined('Illuminate\Http\Request::HEADER_FORWARDED') ? Illuminate\Http\Request::HEADER_FORWARDED : 'forwarded') => 'FORWARDED',
        Illuminate\Http\Request::HEADER_CLIENT_IP    => 'X_FORWARDED_FOR',
        Illuminate\Http\Request::HEADER_CLIENT_HOST  => 'X_FORWARDED_HOST',
        Illuminate\Http\Request::HEADER_CLIENT_PROTO => 'X_FORWARDED_PROTO_CUSTOM',
        Illuminate\Http\Request::HEADER_CLIENT_PORT  => 'X_FORWARDED_PORT_CUSTOM',
    ]

But with 4.0 i can't find a way to specify custom names for  HEADER_CLIENT_PORT and HEADER_CLIENT_PROTO

Does someone know how to deal with this issue ?

thx

**Comment by fideloper** [comment]
Symfony took away our ability to use custom headers :(

What headers are set in your case?

**Comment by olivM** [comment]
My site is hosted on AWS, the laravel app servers are behind a varnish/nginx proxy cache
We need to keep a http only version of the site (even if the public is https only)

So to be able to be aware of the real http scheme, the X-Forwarded-(Proto|Port) headers are forwarded as X-Forwarded-(Proto|Port)-Custom 

```
 if (req.http.X-Forwarded-Proto) {
    set req.http.X-Forwarded-Proto-Custom = req.http.X-Forwarded-Proto;
}
```

I've asked again the AWS guys, but it seems that we can't rely on the default headers

**Comment by fideloper** [comment]
Gotcha! So....I'm not sure Symfony will actually allow us to to read the `X-Forwarded-Proto-Custom` header instead of the `X-Forwarded-Proto` header.

I may be wrong, but I haven't seen how to adjust the headers in Symfony 4, short of extending the Request class and changing the header (although I'm not sure how feasible extending that class is).

I've been a bit miffed about that myself, it seems insane to me to ignore how often developers are stuck behind custom setups like this that you can't easily change.

Would it be possible to use the `X-Forwarded-*` headers and create a [`Forwarded`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Forwarded) header that Symfony does allow?

```
if (req.http.X-Forwarded-Proto) {
    set req.http.Forwarded = "proto=req.http.X-Forwarded-Proto";
}
```

(I'm not sure on the syntax for that exactly)

**Comment by olivM** [comment]
yes i tried to extend the HttpFoundation\Request but can't find a way to do it cleanly
so for now i just patch the class, after composer install/update ... 

i'll will open a issue on Symfony directly (but no hope they'll change this in a near future... )

using the default X-Forwarded-Proto will cause Symfony to think that the request is actually https, and it will start a redirect loop :/

thx

**Comment by IlCallo** [comment]
Hey @fideloper are you aware of [this](https://github.com/jdavidbakr/CloudfrontProxies)?
It describes exactly the problem I'm having (and a lot of others probably) when the application is behind CDN **and** a load balancer.

Maybe you could speak to the maintainer and find a way to add a "customize headers" part into your package, while we wait for Symfony to rethink their decision.

**Comment by fideloper** [comment]
See https://github.com/jdavidbakr/CloudfrontProxies/issues/1 for some notes on how I solved this. I might add this to documentation (in addition to suggesting this package).

Altho I like the approach used in that package as well! We'll see.

**Comment by imbrish** [comment]
I dealt with this by extending `TrustProxies` middleware:
```php
/**
 * The mapping of custom and standard header names.
 *
 * @var array
 */
protected $aliases = [
    // Host header used by ngrok.
    'HTTP_X_ORIGINAL_HOST' => 'HTTP_X_FORWARDED_HOST',
];

/**
 * Handle an incoming request.
 *
 * ...
 */
public function handle(Request $request, Closure $next)
{
    foreach ($this->aliases as $custom => $standard) {
        if (! $request->server->has($standard) && $value = $request->server->get($custom)) {
            $request->server->set($standard, $value);
            $request->headers->set(substr($standard, 5), $value); // Remove "HTTP_" prefix.
        }
    }

    return parent::handle($request, $next);
}
```

@fideloper would you be interested in merging this if I send a PR?

**Comment by fideloper** [comment]
I'll see, this also affects core Laravel as it has it's own middleware that incorporates this one. Thanks!

**Comment by fideloper** [comment]
You have the `x-forwarded-proto` header which this package should use automatically. However you haven't told us what version of Laravel you're using, and or what your code setup is (if you're using the built-in middleware in laravel and if so, how you configured it).

**Comment by griffins** [comment]
I am using the inbuilt middleware, laravel 5.6.33

My Php version
```PHP 7.2.8 (cli) (built: Jul 28 2018 17:55:09) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.8, Copyright (c) 1999-2018, by Zend Technologies
```

**Comment by rodruiz** [comment]
Hi,
the issue could be your nginx configuration.
You can check my boilerplate in more details [here](https://github.com/rrpadilla/laravel-adminlte-boilerplate).
- [config/trustedproxy.php](https://github.com/rrpadilla/laravel-adminlte-boilerplate/blob/master/config/trustedproxy.php)
- [TrustProxies Middleware](https://github.com/rrpadilla/laravel-adminlte-boilerplate/blob/master/app/Http/Middleware/TrustProxies.php)

This configuration is working perfectly fine for me.

LARAVEL .ENV
```env
TRUSTEDPROXY_PROXIES="*"
TRUSTEDPROXY_HEADERS="HEADER_X_FORWARDED_AWS_ELB"
```

LARAVEL [TrustProxies](https://github.com/rrpadilla/laravel-adminlte-boilerplate/blob/master/app/Http/Middleware/TrustProxies.php) MIDDLEWARE
```php
<?php
namespace App\Http\Middleware;

use Illuminate\Http\Request;
use Illuminate\Contracts\Config\Repository;
use Fideloper\Proxy\TrustProxies as Middleware;

class TrustProxies extends Middleware
{
    /**
     * Create a new trusted proxies middleware instance.
     *
     * @param \Illuminate\Contracts\Config\Repository $config
     */
    public function __construct(Repository $config)
    {
        parent::__construct($config);
        $this->proxies = config('trustedproxy.proxies');
        $this->headers = config('trustedproxy.headers');
    }
}
```

NGINX
```nginx
server {
    # all traffic, secure or otherwise, comes in on 80 from the ELB
    listen 80;
    server_name YOUR-DOMAIN.COM;
    root /home/USERNAME/sites/YOUR-DOMAIN/public;

    # ELB stores the protocol used between the client
    # and the load balancer in the X-Forwarded-Proto request header.
    # Check for 'https' and redirect if not
    if ($http_x_forwarded_proto != 'https') {
        return 301 https://$server_name$request_uri;
    }
    .......
}
```
Let me know if that works for you.

Thinking on pushing the updated middleware + config file to laravel repo.

Thanks.

**Comment by rrpadilla** [comment]
Hi,
maybe this [PR](https://github.com/laravel/laravel/pull/4799) to laravel repo will help :)
