### ISSUE TITLE
Publish command not working

### ISSUE THREAD

**Issue by Oscar-21** [fideloper/TrustedProxy#110]
I am on Laravel Framework 5.4.21.
I installed the package using this command
```
composer require fideloper/proxy
```
The publish command said it was "complete".
```
php artisan vendor:publish --provider="Fideloper\Proxy\TrustedProxyServiceProvider"
Publishing complete.
```
My config folder was not updated with any file though.
Any thoughts? Am I doing something wrong?

**Comment by fideloper** [comment]
Try removing the package and re-installed at tag 2.0+: 

```bash
composer require fideloper/proxy:~2.0
```

**Comment by Oscar-21** [comment]
Thanks before you posted this I saw in the readme you recommended people on my version of laravel to update their composer.json to 
```
{
    "require": {
        "fideloper/proxy": "^3.3"
    }
}
``` 
So I ran
``` 
composer require "fideloper/proxy:^3.3"
```
Now everything is working!

**Comment by fideloper** [comment]
Great!
