### ISSUE TITLE
QUESTION How to make sure this is working properly?

### ISSUE THREAD

**Issue by MickaelTH** [fideloper/TrustedProxy#114]
Hi,

I followed the installation but wonder how to be sure this is installed correctly?

Is there any way to check if all setups are fine?

Thanks.

**Comment by fideloper** [comment]
Hi!

I'm hoping to release a little debugger tool (see the [feature/debugger](https://github.com/fideloper/TrustedProxy/tree/feature/debugger) branch) that adds a route with some helpers to be able to tell.

Generally what it involves is checking `$_SERVER` to see what `HTTP_` items (http headers) PHP is receiving, and then doing a few things to ensure Laravel creates URLs correctly (using https when it should, for example).

* `request()->getClientIp()` should return the results of `X-Forwarded-For` (`$_SERVER['HTTP_X_FORWARDED_FOR']`)
* `request()->getScheme()` should return the results of `X-Forwarded-Proto` (`$_SERVER['HTTP_X_FORWARDED_PROTO']`)
* `url('/foo-bar')` should create URL's correctly (http/s as appropriate, correct hostname)

**Comment by MickaelTH** [comment]
Hey (2 years later).

Thanks for the answer, forgot to close it :)
