### ISSUE TITLE
laravel 5.4 behind an IBM load balancer

### ISSUE THREAD

**Issue by sgdmediagroup** [fideloper/TrustedProxy#120]
Hi!

I'm running 2 laravels behind an IBM Load Balancer and i cant get Trustedproxy to work. I've tried all the configs mentioned in previous issues but i cant make it work. 

thanks!

**Comment by fideloper** [comment]
Hi!

Can you dump out your `$_SERVER` global within laravel when you're behind the load balancer?

**Comment by sgdmediagroup** [comment]
yes 

array:35 [▼
  "USER" => "www-data"
  "HOME" => "/var/www"
  "HTTP_X_FORWARDED_FOR" => "186.105.67.85"
  "HTTP_COOKIE" => "XSRF-TOKEN=eyJpdiI6IncwaEJOYmVmT0FBaDhUaVBXZEs1bmc9PSIsInZhbHVlIjoiQTVuS0NxNFpDR1J1dStOYjBSNURSemlxUHg4UFgrRmVOZ0FzbHdHMGFobG9GaG0xaENDSGVvY2FZMmt1eTBiZ0oxc2daZ ▶"
  "HTTP_ACCEPT_LANGUAGE" => "en-US,en;q=0.9"
  "HTTP_ACCEPT_ENCODING" => "gzip, deflate"
  "HTTP_ACCEPT" => "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8"
  "HTTP_USER_AGENT" => "Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.81 Safari/537.36"
  "HTTP_UPGRADE_INSECURE_REQUESTS" => "1"
  "HTTP_CACHE_CONTROL" => "max-age=0"
  "HTTP_HOST" => "explora-lb-1-1831755-sao01.lb.bluemix.net"
  "REDIRECT_STATUS" => "200"
  "SERVER_NAME" => "_"
  "SERVER_PORT" => "80"
  "SERVER_ADDR" => "10.151.62.8"
  "REMOTE_PORT" => "41362"
  "REMOTE_ADDR" => "10.151.62.21"
  "SERVER_SOFTWARE" => "nginx/1.10.3"
  "GATEWAY_INTERFACE" => "CGI/1.1"
  "REQUEST_SCHEME" => "http"
  "SERVER_PROTOCOL" => "HTTP/1.1"
  "DOCUMENT_ROOT" => "/var/www/html/explora-registros/public"
  "DOCUMENT_URI" => "/index.php"
  "REQUEST_URI" => "/login"
  "SCRIPT_NAME" => "/index.php"
  "CONTENT_LENGTH" => ""
  "CONTENT_TYPE" => ""
  "REQUEST_METHOD" => "GET"
  "QUERY_STRING" => ""
  "SCRIPT_FILENAME" => "/var/www/html/explora-registros/public/index.php"
  "PATH_INFO" => ""
  "FCGI_ROLE" => "RESPONDER"
  "PHP_SELF" => "/index.php"
  "REQUEST_TIME_FLOAT" => 1548883390.0673
  "REQUEST_TIME" => 1548883390
]

thanks for the quick reply.

**Comment by fideloper** [comment]
Thanks - here's what I believe is relevant:

**Good:**

* `HTTP_X_FORWARDED_FOR` is present, that's good - the IP address should be the actual IP of the client making the HTTP request (looks like it probably is, but I can't know for sure)

**Bad:**

* No other `HTTP_X_FORWARDED` headers are present, to Trusted Proxy won't be able to know about the correct protocol (`http` vs `https`)
    * `HTTP_X_FORWARDED_PROTO` ideally is present to know `http` vs `https` (Laravel needs this header to know the correct way to general URLs)
* `HTTP_HOST` looks like it's the hostname of the load balancer, but it should be set to the hostname used to make the HTTP request. Laravel may generate/use the wrong hostname to generate URL's as it is now.
    * If not, then a `X_FORWARDED_HOST` should be present that the correct hostname


> Note that variables `HTTP_*` relate to HTTP host headers, so `HTTP_X_FORWARDED_FOR` relates to the `X-Forwarded-For` header and `HTTP_X_FORWARDED_PROTO` relates to the `X-Forwarded-Proto` HTTP header

So, I would contact whoever you can who helps administer the load balancer to see if it's possible for extra options to be added for the following headers:

* `X-Forwarded-Proto` and set it to `https` if you're using an SSL certificate
* `X-Forwarded-Host` to the host being used by clients to make HTTP requests

**Comment by sgdmediagroup** [comment]
Thanks. I created a ticket asking to the provider if it is possible to add the headers that you mentioned.

Besides that, could you elavorate more in what i should do in order to make it work? For now i dont really need to make it dynamic so it knows if im using http or https, i just need this to work.

Thanks!

**Comment by fideloper** [comment]
I don't have time to figure it all out for you, I apologize.

The general steps will be:

1. `php artisan make:middleware` (that command may be different in laravel 5.4)
2. Find appropriate methods on the [Laravel Request class](https://github.com/laravel/framework/blob/5.4/src/Illuminate/Http/Request.php), and potentially [underlying Symfony class](https://github.com/symfony/http-foundation/blob/v3.2.14/Request.php) to allow you to set the Host and Scheme / Protocol

It may simply be as easy as setting `$_SERVER` variables to what you want them to be I'm not sure - it may take some experimentation and googling.

**Comment by sgdmediagroup** [comment]
thank you for your time!

**Comment by fideloper** [comment]
You're welcome, happy to help as I can!

**Comment by sgdmediagroup** [comment]
hey  fideloper...

I created the middleware that runs before your plugin. I'm replacing the **REMOTE_ADDR** for the HTTP_X_FORWARDED and im setting everything else to null, cuz ibm don't give me any response. 

    public function handle($request, Closure $next)
    {
        if( isset($_SERVER['HTTP_X_FORWARDED_FOR']) ) {

            $request->setTrustedHeaderName(Request::HEADER_FORWARDED, null);
            $request->setTrustedHeaderName(Request::HEADER_CLIENT_HOST, null);
            $request->setTrustedHeaderName(Request::HEADER_CLIENT_PROTO, null);
            $request->setTrustedHeaderName(Request::HEADER_CLIENT_PORT, null);    
            $request->server->set('REMOTE_ADDR', $_SERVER['HTTP_X_FORWARDED_FOR']);

        }

        return $next($request);

dont know if you see something i could do to make this work... 
thanks!

**Comment by tnatanael** [comment]
i Used this headers in nginx and it finnaly worked
location / {
        proxy_set_header X-Forwarded-Host $http_host;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header X-Forwarded-Proto https;
        proxy_pass https://destination/;
    }
