### ISSUE TITLE
Assets return in HTTP scheme which causes Mixed-Content issues

### ISSUE THREAD

**Issue by Binternet** [fideloper/TrustedProxy#122]
I'm using `Laravel 5.4` with trustedproxy,
Here's my `config/trustedproxies.php` :
```
return [
    'proxies' => '*', # Trust all proxies

    'headers' => [
        \Illuminate\Http\Request::HEADER_FORWARDED    => 'FORWARDED',
        \Illuminate\Http\Request::HEADER_CLIENT_IP    => 'X_FORWARDED_FOR',
        \Illuminate\Http\Request::HEADER_CLIENT_HOST  => 'X_FORWARDED_HOST',

        # 2. Adjust to CloudFront's header
        \Illuminate\Http\Request::HEADER_CLIENT_PROTO  => 'CLOUDFRONT_FORWARDED_PROTO', 
    ]
];
```

Yet i'm still getting `http` instead of `https`, when I print my `$_SERVER` var I see this:
```
'REQUEST_SCHEME' => 'http',
...
  'HTTP_CLOUDFRONT_FORWARDED_PROTO' => 'https',
```

And I think that's the issue. any ideas why?

**Comment by Binternet** [comment]
I think I managed to solve it by adding:

```
map $http_cloudfront_forwarded_proto $cloudfront_proto {
    default "http";
    https "https";
}
```

and then this:
`fastcgi_param HTTP_X_FORWARDED_PROTO $cloudfront_proto;`
in the `location ~ \.php$` block

**Comment by fideloper** [comment]
That looks good, I do the same myself with cloudfront!

**Comment by Binternet** [comment]
@fideloper That's because I took this snippet from your article! ;-)
Keep up the great work!
