### ISSUE TITLE
Automatically included in Laravel 5.5+ via what package?

### ISSUE THREAD

**Issue by callum-ez** [fideloper/TrustedProxy#134]
I'm just wondering where the automatic inclusion comes from in Laravel 5.5+. For Laravel 7, it is not a direct dependency, which means it must be included as a dependency of a dependency somewhere.

I'm upgrading an old project to Laravel 7 and took this dependency out of composer.json because it claims to not be needed anymore, but now I'm getting "Class 'Fideloper\Proxy\TrustProxies' not found" errors.

Obviously I could easily fix this by adding this package to my composer.json, but if this is supposed to be included as a dependency of something else, I'm worried I'd still be missing whatever that something else is.

**Comment by fideloper** [comment]
It needs to be in composer.json. You just don’t need to”require” it
yourself because Laravel has it there already.
