### ISSUE TITLE
Error after update to version 4.4 

### ISSUE THREAD

**Issue by DaniloBenevides** [fideloper/TrustedProxy#136]
I'm using Laravel 5.8 and after this lib updated to version 4.4 I got the following error:

Argument 2 passed to Symfony\Component\HttpFoundation\Request::setTrustedProxies() must be of the type integer, array given, called in vendor/fideloper/proxy/src/TrustProxies.php on line 54

I could not reproduce this issue on 4.3

There is something that I should do?

Thanks in advice,

**Comment by fideloper** [comment]
hi! What’s your trustproxies middleware have in it?

**Comment by DaniloBenevides** [comment]
<?php

namespace App\Http\Middleware;

use Illuminate\Http\Request;
use Fideloper\Proxy\TrustProxies as Middleware;

class TrustProxies extends Middleware
{
    /**
     * The trusted proxies for this application.
     *
     * @var array
     */
    protected $proxies;

    /**
     * The current proxy header mappings.
     *
     * @var array
     */
    protected $headers = [
        Request::HEADER_FORWARDED => 'FORWARDED',
        Request::HEADER_X_FORWARDED_FOR => 'X_FORWARDED_FOR',
        Request::HEADER_X_FORWARDED_HOST => 'X_FORWARDED_HOST',
        Request::HEADER_X_FORWARDED_PORT => 'X_FORWARDED_PORT',
        Request::HEADER_X_FORWARDED_PROTO => 'X_FORWARDED_PROTO',
    ];
}

**Comment by fideloper** [comment]
Thanks!

For the $headers variable, and those settings, please use this in Laravel 5.8:

https://github.com/laravel/laravel/blob/5.8/app/Http/Middleware/TrustProxies.php#L22

`protected $headers = Request::HEADER_X_FORWARDED_ALL;`
