### ISSUE TITLE
Argument 2 passed to Symfony\Component\HttpFoundation\Request::setTrustedProxies() must be of the type integer, array given

### ISSUE THREAD

**Issue by keringdered** [fideloper/TrustedProxy#137]
After an upgrade to version 4.4 there is an override of parameters(Array) required by the earlier versions. How should this be fixed?

**Comment by fideloper** [comment]
Hi!

What version of Laravel are you using? Please check the TrustProxies middleware for your Laravel version to see if it needs updating. If you've customized that setting, let me know.

**Comment by keringdered** [comment]
PHP 7.2
Laravel 5.8

**Comment by keringdered** [comment]
I found a way out on the same problem
