### ISSUE TITLE
Call to a member function get() on null

### ISSUE THREAD

**Issue by khavishbhundoo** [fideloper/TrustedProxy#138]
I am using laravel 7.x and i am trying to set value for $proxies in a constructor in the TrustProxies middleware.I get the following

`Call to a member function get() on null` on line 67  which is `$trustedIps = $this->proxies ?: $this->config->get('trustedproxy.proxies');`

**Comment by fideloper** [comment]
Hi!

If you’re using the constructor, where/how is the classes $config object
being set? It sounds like there’d be an issue there. Perhaps try the
“config()” helper.

However there’s a chance that middlewares are created early on the
bootstrapping and so config isn’t available in the constructor.

**Comment by khavishbhundoo** [comment]
In Laravel 7.x , the TrustProxies is the first middleware in the global middleware stack

```
/**
     * The application's global HTTP middleware stack.
     *
     * These middleware are run during every request to your application.
     *
     * @var array
     */
    protected $middleware = [
        \App\Http\Middleware\TrustProxies::class,
        \App\Http\Middleware\CheckForMaintenanceMode::class,
        \Illuminate\Foundation\Http\Middleware\ValidatePostSize::class,
        \App\Http\Middleware\TrimStrings::class,
        \Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull::class,
    ]; 
```

**Comment by fideloper** [comment]
Hi!

Laravel comes with it's own HTTP middleware for this package since Laravel 5.5. 

It sounds like  you've extended the constructor in your version. The original constructor is:

```php
public function __construct(Repository $config)
{
    $this->config = $config;
}
```

If you over-write the constructor without type-hinting `Illuminate\Contracts\Config\Repository`, you'll receive that error. Unfortunately running `parent::__construct()` isn't enough in that case.


> It's also possible you've published the TrustedProxies middleware instead of using Laravel's default, which is also incorrect as of Laravel 5.5.

**Comment by khavishbhundoo** [comment]
I was not passing type hinting  `Illuminate\Contracts\Config\Repository` as you correctly pointed out.
