### ISSUE TITLE
Undefined constan HEADER_X_FORWARDED_ALL Laravel 9

### ISSUE THREAD

**Issue by fh32000** [fideloper/TrustedProxy#149]
Laravel 9 
php 8.0.15
"fideloper/proxy": "^4.4.1",
Undefined constant Illuminate\Http\Request::HEADER_X_FORWARDED_ALL

**Comment by fideloper** [comment]
In Laravel 9, the Laravel team pulled this functionality into the framework, and so this package is no longer needed.

* The laravel/laravel project: https://github.com/laravel/laravel/blob/master/app/Http/Middleware/TrustProxies.php
* The larave/framework middleware:  https://github.com/laravel/framework/blob/master/src/Illuminate/Http/Middleware/TrustProxies.php

**Comment by fideloper** [comment]
(Specifically that constant `HEADER_X_FORWARDED_ALL` was likely removed in the base Symfony classes, rather than from Laravel itself).
