### ISSUE TITLE
Illuminate\Http\Request::HEADER_X_FORWARDED_ALL

### ISSUE THREAD

**Issue by qdmitry** [fideloper/TrustedProxy#150]
I instal latest version 4.4.1, but error.

<img width="1239" alt="Снимок экрана 2022-02-09 в 11 48 31" src="https://user-images.githubusercontent.com/28624280/153137002-8c039730-a59b-468c-9eaa-ea662ea6ef14.png">

**Comment by qdmitry** [comment]
I don't understand why the code doesn't match the master branch.

<img width="1659" alt="Снимок экрана 2022-02-09 в 12 06 59" src="https://user-images.githubusercontent.com/28624280/153139452-14ad77b0-7a9a-413b-bb9a-01ddea034167.png">

**Comment by edsaunders92** [comment]
See Issue #149

For laravel 9 this package is no longer needed so simply remove it

**Comment by qdmitry** [comment]
@edsaunders92 Take a closer look at the problem! My project files are fine. The problem is loading from composer.

**Comment by qdmitry** [comment]
<img width="1664" alt="153143687-87bc16c3-b973-4f96-9226-59d837174994" src="https://user-images.githubusercontent.com/28624280/153144757-f7216b1c-077e-4d4d-8f0c-1fe1a9c316d1.png">

**Comment by omidxplimbo** [comment]
i can't install this package for laravel 9 please help me

**Comment by qdmitry** [comment]
Please make following changes
file: app/Http/Middleware/TrustProxies.php
```
use Fideloper\Proxy\TrustProxies as Middleware 
to 
use Illuminate\Http\Middleware\TrustProxies as Middleware.
```

for Laravel 9, this package is no longer needed.
