### ISSUE TITLE
is Fideloper's TrustedProxy on Laravel 5.5.43?

### ISSUE THREAD

**Issue by ArianHojatAES** [fideloper/TrustedProxy#156]
Documentation seems to imply its on 5.5 but i dont see... Im on  Laravel 5.5.43.
I don't seem to see a  App\Http\Middleware\TrustProxies.php file at all, so I'd thought i'd ask how to get it in.

**Comment by fideloper** [comment]
Laravel 5.5 includes it, but if you updated to 5.5 from an earlier version, you may have missed adding it to your `composer.json` file?

https://github.com/laravel/laravel/blob/5.5/composer.json#L9

**Comment by ArianHojatAES** [comment]
gotcha that was prob it, as we upgraded from 5.x to 5.5. I'll put in the composer and run update and see what else i have to do after. Thanks!
