### ISSUE TITLE
laravel 10 upgrading issue

### ISSUE THREAD

**Issue by mdzahid-pro** [fideloper/TrustedProxy#159]
Problem 1
    - Conclusion: don't install fideloper/proxy 4.4.2 (conflict analysis result)
    - illuminate/contracts[v5.6.0, ..., 5.8.x-dev] require php ^7.1.3 -> your php version (8.2.8) does not satisfy that requirement.
    - illuminate/contracts[v6.0.0, ..., v6.19.1] require php ^7.2 -> your php version (8.2.8) does not satisfy that requirement.
    - illuminate/contracts[v7.0.0, ..., v7.28.4] require php ^7.2.5 -> your php version (8.2.8) does not satisfy that requirement.
    - illuminate/contracts[v8.0.0, ..., v8.11.2] require php ^7.3 -> your php version (8.2.8) does not satisfy that requirement.
    - Root composer.json requires fideloper/proxy ^4.4 -> satisfiable by fideloper/proxy[4.4.0, 4.4.1, 4.4.2].

**Comment by fideloper** [comment]
This package is part of core laravel as of Laravel 9 and no longer needs
installing. See app/Http/Middleware/TrustProxies.php

* here is the middleware: https://github.com/laravel/laravel/blob/10.x/app/Http/Middleware/TrustProxies.php
* and it's included in the web requests here: https://github.com/laravel/laravel/blob/10.x/app/Http/Kernel.php#L18
