### ISSUE TITLE
Proxy fix not working for redirectIfTrailingSlash check

### ISSUE THREAD

**Issue by ArthurGuy** [fideloper/TrustedProxy#2]
Early in Laravel's startup the method redirectIfTrailingSlash is executed (top of start.php), this seems to be happening before the proxy fix gets put in place resulting in a broken ssl redirect.

I imagine this is happening too early for this library to fix but I thought I would check.
Thanks

**Comment by fideloper** [comment]
Closing for now, but lmk if you find an issue with this related to the trailing slash!
