### ISSUE TITLE
Support Laravel 5

### ISSUE THREAD

**Issue by GrahamCampbell** [fideloper/TrustedProxy#22]
Currently we're broken on Laravel 5. We need to support the new config registration.

**Comment by fideloper** [comment]
Cool. I haven't touched L5 yet at all :P (other than to look at it and see the screencasts) - 
I think more so than answer "how to support l5" is "how to support both 4.* series and 5".

Any ideas?

**Comment by GrahamCampbell** [comment]
I'd recommend making a new major version for Laravel 5. The config stuff is totally different.

**Comment by fideloper** [comment]
Tracking laravel 5 updates on the `develop` branch: https://github.com/fideloper/TrustedProxy/tree/develop

**Comment by fideloper** [comment]
See #develop branch, closing this for now.
