### ISSUE TITLE
Remove Laravel Version from Package Description

### ISSUE THREAD

**Issue by vinkla** [fideloper/TrustedProxy#29]
It currently says "Laravel 4 Proxy Package for handling…". Maybe we could update it to "Laravel Proxy Package for handling…" to show that it works with all kinds of Laravel :)

**Comment by fideloper** [comment]
Definitely, BUT -- I can't find that anywhere! Are you seeing that on packagist? in a file here?

Thanks

**Comment by vinkla** [comment]
Sorry, didn't say it was here on GitHub. Just below the title.

**Comment by fideloper** [comment]
Ah, of course!

Updated, thanks!

**Comment by vinkla** [comment]
Nice!
