### ISSUE TITLE
possible to handle proxy from localhost:9000?

### ISSUE THREAD

**Issue by Kaijun** [fideloper/TrustedProxy#33]
Hello,

I'm using Laravel + Angular(with Gulp) in my project.
But it's always being a problem when i wanna request the APIs provided by Laravel.
Our frontend project is using Gulp, which will start a simple server on 9000 port in development, but the lavarel owns 8000 port.

so can i use this plugin to handle proxy from localhost:9000 (my simple gulp server for Angular)?

**Comment by GrahamCampbell** [comment]
Trusted proxies are for ips not for hostnames. :0

**Comment by vluzrmos** [comment]
You tried to use the machine or virtual IP 127.0.0.1?
And I think you need a [Cors Package](https://github.com/barryvdh/laravel-cors), not only that.

**Comment by fideloper** [comment]
Yep, if javascript is running on a server listening on port 8000 and the api is running on port 9000, you're technically (in the eyes of browsers) sending requests between two different hostnames. Browsers will block this unless the API signals it's OK via CORS headers, as linked above.

That's not the problem this project is solving, however!
