### ISSUE TITLE
Ready To Run App

### ISSUE THREAD

**Issue by alimasyhur** [fideloper/TrustedProxy#36]
Do you ready application with TrustedProxy for us with just clone it into our machine?
And the demo as well.

Thanks in advanced.

**Comment by fideloper** [comment]
You'll need to configure TrustedProxy after installing it into your Laravel application. Follow the [TL;DR Setup](https://github.com/fideloper/TrustedProxy#tldr-setup) steps to do that.

This is meant to be used within a Laravel application.
