### ISSUE TITLE
Problem with redirect() from Laravel being always http

### ISSUE THREAD

**Issue by crash13override** [fideloper/TrustedProxy#48]
If I try to wget the root folder of my app page, then it will redirect me to the /login page via Laravel's redirect() helper method.

I have a web server behing a load balancer that is the endopoint for SSL. When I open the root url of my app, I get redirected to the /login page if not logged in, an everything works fine and the final result is as expected (I get redirected properly)

But what happens behind the scene is the following:
1) I ask for https://app.workstack.io
2) Load balancer forwards it to the web server that responds with a redirect to HTTP://app.workstack.io/login
3) Request is sent to the Load Balancer that redirects again to HTTPS://app.workstack.io/login
4) Finally the request goes through the web server and I output the login page.

My question is: Is it possible in some way to avoid the extra redirect from http to https?
I think it's a similar problem like when using the url() helper, where you need to replace it with secure_url() or it will be output with http instead of https. Is there a way to tell Laravel to use always https by default for all the url generated by its helper methods? (url(), redirect(), etc.)

I copy here the wget of the request so that it get be more clear

wget https://app.workstack.io
--2016-06-09 22:08:37--  https://app.workstack.io/
Resolving app.workstack.io (app.workstack.io)... 174.143.185.9
Connecting to app.workstack.io (app.workstack.io)|174.143.185.9|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: http://app.workstack.io/login [following]
--2016-06-09 22:08:37--  http://app.workstack.io/login
Connecting to app.workstack.io (app.workstack.io)|174.143.185.9|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://app.workstack.io/login [following]
--2016-06-09 22:08:37--  https://app.workstack.io/login
Connecting to app.workstack.io (app.workstack.io)|174.143.185.9|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘index.html.3’

Thanks a lot for this awesome library btw! :)

**Comment by GrahamCampbell** [comment]
Have you set the config correctly, and added the middleware? Have you also correctly set the app url in the env file?

**Comment by GrahamCampbell** [comment]
I am using this package on https://styleci.io/, and that sits behind CloudFlare. Adding the middleware and cloudflare's IPs allows it to work correctly.

**Comment by crash13override** [comment]
yes, I set up all the things you mentioned and double checked everything.
Before I used this package, the website was not working at all, so I think it's working as expected.
It's just a minor detail that could be improved, but I'm not sure if it's something too specific of Laravel's helper method (url(), redirect(),..) that the package can't override.

Out of curiosity: do you use some of this helpers somewhere? You didn't have to use secure_url() instead for example?

thanks!

**Comment by GrahamCampbell** [comment]
> You didn't have to use secure_url() instead for example?

No, I don't call secure url.

**Comment by crash13override** [comment]
mmh... then it must be something with the header not forwarded properly by Rackspace load balancer perhaps

**Comment by crash13override** [comment]
This is my config file


    'proxies' => '*',

    'headers' => [
        \Illuminate\Http\Request::HEADER_CLIENT_IP    => 'X_FORWARDED_FOR',
        \Illuminate\Http\Request::HEADER_CLIENT_HOST  => 'X_FORWARDED_HOST',
        \Illuminate\Http\Request::HEADER_CLIENT_PROTO => 'X_FORWARDED_PROTO',
        \Illuminate\Http\Request::HEADER_CLIENT_PORT  => 'X_FORWARDED_PORT',
    ]

**Comment by GrahamCampbell** [comment]
have you added the middleware?

**Comment by GrahamCampbell** [comment]
> 'proxies' => '*',

That's a bad idea btw.

**Comment by crash13override** [comment]
yes, I have it in the middleware as well in the 'web' group.

In the config file I had 'proxies' set to the IP of the server before, but then I tried with '*' after reading this wiki
https://github.com/fideloper/TrustedProxy/wiki/IP-Addresses-of-Popular-Services

gonna put it back to the IP now that I know it doesn't solve the problem...

**Comment by fideloper** [comment]
Let us know if you still have issues (Grabbing the latest code may help as well).

**Comment by peppeocchi** [comment]
@fideloper I'm having the same issue, our configuration is similar to @crash13override 

- Laravel (5.1) on AWS Elastic Beanstalk
- AWS CloudFront (pointing to the ELB dns)

All the urls are being generated like
`http://my.website.com:443/some-page`

This is our configuration 
```php
'proxies' => '**',

'headers' => [
        (defined('Illuminate\Http\Request::HEADER_FORWARDED') ? Illuminate\Http\Request::HEADER_FORWARDED : 'forwarded') => null,
        Illuminate\Http\Request::HEADER_CLIENT_IP    => 'X_FORWARDED_FOR',
        Illuminate\Http\Request::HEADER_CLIENT_HOST  => null,
        Illuminate\Http\Request::HEADER_CLIENT_PORT  => 'X_FORWARDED_PORT',

        // We tried with and without the following
        Illuminate\Http\Request::HEADER_CLIENT_PROTO  => 'CLOUDFRONT_FORWARDED_PROTO',
    ]
```

Any idea? I'll try other configurations, right now I've solved it with a [more basic middleware](https://github.com/peppeocchi/laravel-elb-middleware/blob/master/src/GO/ElasticBeanstalkHttps.php).

**Comment by fideloper** [comment]
Hey @peppeocchi - Can you check https://github.com/fideloper/TrustedProxy/issues/87 and see if using the branch with the debugger helps? It should show you what your application is seeing, allowing you to adjust as needed.

Since you have two proxies in place there could be some confusion on which headers its grabbing and which its seeing / are correct.

**Comment by peppeocchi** [comment]
@fideloper thank your for your reply, I'll try with that branch and I'll let you know if I find something.

**Comment by fideloper** [comment]
Appreciate it!

Some people have reported success setting the trusted proxy to `['0.0.0.0/0']` - give that a try as well.

**Comment by peppeocchi** [comment]
@fideloper what fixed the issue for me was moving the `TrustProxies` middleware on top of the stack, I haven't had any issue since then!

```php
    protected $middleware = [
        'Fideloper\Proxy\TrustProxies',
        // other middlewares
    ],
```

Other than the port number, something else that happened was that on some pages the generated urls were `http` instead of `https`, the reason was that one of the middlewares before TrustProxies was calling a controller method (only under certain conditions) and not following the chain.
Moving it on top of the stack fixed every issue.

**Comment by fideloper** [comment]
ohhh interesting, thanks for letting me know! Definitely useful.
