### ISSUE TITLE
Incorrect assumptions about X-Forwarded-For

### ISSUE THREAD

**Issue by kpcyrd** [fideloper/TrustedProxy#49]
As noted in #46, `X-Forwarded-For` is actually used in a different way than described in the README.md, see [X-Forwarded-For](https://en.wikipedia.org/wiki/X-Forwarded-For#Format).

This header doesn't necessarily contain a single ip address, it also contains the ip addresses of intermediate proxies. So if the client is on a corporate network (or uses the [google compression proxy](https://developer.chrome.com/multidevice/data-compression#faq), to name a specific example) and you're using a loadbalancer, this header might look like this:

```
X-Forwarded-For: 10.1.2.23, 5.4.3.2, 10.9.8.7.69
```

This is necessary because in the event of abuse, you would start from the right side, `10.9.8.7.69` belongs to your network, if `5.4.3.2` turns out to be a legitimate proxy, they would check who belongs to `10.1.2.23`, otherwise they might have spoofed the `10.1.2.23` part, which you can't verify.

I'm not sure if it's feasible to determine the value you would actually expect, unless there's extra configuration but I'm not sure that's the right way. Ideally, there would be an extra header that is set/overwritten on your loadbalancer.

**Comment by tamc** [comment]
I think this issue should be closed. It is only making an incorrect assumption in the case where `'proxy' => '*'` and even that is probably a judgement call about what is meant. See my response in #46
