### ISSUE TITLE
Laravel 4.1 site and the fix for HTTPPoxy

### ISSUE THREAD

**Issue by zodthepossum** [fideloper/TrustedProxy#51]
Does anyone have some instructions on how to apply the fideloper fix for HTTPPoxy on Laravel 4.1?

I have a Laravel 4.1 site, that of course has no middleware, and am wondering if is vunerable. I've never been able to successfully serve it up over https either.

https://laracasts.com/discuss/channels/laravel/enable-https-via-cloudflare-on-laravel-41-app

**Comment by fideloper** [comment]
Apologies for not responding to this, did you end up with a solution? 

The [latest v2](https://github.com/fideloper/TrustedProxy/tree/2.1.1) tag should work in Laravel 4.1
