### ISSUE TITLE
Needs docs for Forwarded header

### ISSUE THREAD

**Issue by dzuelke** [fideloper/TrustedProxy#52]
Symfony has been supporting the `Forwarded` header for a while. It should be documented explicitly, added to the defaults in the config, and there should be a big warning advising people to potentially set that to `null` if their load balancer doesn't support that header yet (e.g. AWS ELB, or Heroku), as otherwise, Symfony will trust it and attackers can spoof client IPs.

**Comment by dzuelke** [comment]
See https://devcenter.heroku.com/articles/getting-started-with-laravel#trusting-the-load-balancer and https://symfony.com/doc/current/request/load_balancer_reverse_proxy.html#my-reverse-proxy-sends-x-forwarded-for-but-does-not-filter-the-forwarded-header for more info

**Comment by fideloper** [comment]
Will check that out, thanks!

**Comment by dzuelke** [comment]
Also, @fideloper, it might be good to note more explicitly in the docs that headers can be un-trusted by setting their values to `null` in the mapping, which is important to do on e.g. AWS, where neither `Forwarded` nor `X-Forwarded-Host` are set by the ELB.

Right now, with the configuration you're advising in the docs, user applications are vulnerable.

**Comment by jarnovanleeuwen** [comment]
The `Forwarded` header is added to the config in https://github.com/fideloper/TrustedProxy/pull/58.

**Comment by fideloper** [comment]
Keeping this open as a TODO for myself to add the information about setting a header as `null` to be un-trusted.
