### ISSUE TITLE
[Question] Terminating SSL on Load Balancer; App creating HTTP links

### ISSUE THREAD

**Issue by doctorallen** [fideloper/TrustedProxy#57]
I have installed the TrustedProxy package into my Laravel app, and am running my application behind a load balancer in Amazon EC2. I am terminating SSL on the load balancer, which is causing my app to create links to itself and assets at HTTP rather than HTTPS. I thought this package would handle that for me, but I'm not entirely sure.

I'm using the default configuration, AWS LB sends the X_Forwarded_For header, I'm not sure about the other headers.

Can anyone give me more info about how to do this, or if this package should do that but I might have a misconfiguration?

**Comment by fideloper** [comment]
Is that an ELB load balancer, or one you have installed yourself on an EC2 instance?

It looks like their days still say ELB headers are as documented here: http://docs.aws.amazon.com/elasticloadbalancing/latest/classic/x-forwarded-headers.html

**Comment by fideloper** [comment]
Specifically I believe the PROTO port is likely used to know if Laravel should respond by generating URL's with `https://`

**Comment by doctorallen** [comment]
It's an ELB Application LB, the new generation. It looks like I'm getting the following:
```
  "HTTP_X_FORWARDED_PORT" => "443"
  "HTTP_X_FORWARDED_PROTO" => "https"
  "HTTP_X_FORWARDED_FOR" => "173.XXX.XXX.XXX"
```

from the `\Request::server()` object. I updated the configurations and added `HTTP_` to the default strings, but It doesn't look like that changed anything.

Do I need to create my own service provider to set the Request to be considered secure by checking the `X-Forwarded-Proto` header myself, or does TrustedProxy do that for me?

**Comment by doctorallen** [comment]
Actually, if I use `\Request::header()` the HTTP is not part of the header name. I guess that's just appended in the server variables.

```
  "cookie" => array:1 [▶]
  "accept-language" => array:1 [▶]
  "accept-encoding" => array:1 [▶]
  "accept" => array:1 [▶]
  "user-agent" => array:1 [▶]
  "upgrade-insecure-requests" => array:1 [▶]
  "authorization" => array:1 [▶]
  "cache-control" => array:1 [▶]
  "x-amzn-trace-id" => array:1 [▶]
  "host" => array:1 [▶]
  "x-forwarded-port" => array:1 [▼
    0 => "443"
  ]
  "x-forwarded-proto" => array:1 [▼
    0 => "https"
  ]
  "x-forwarded-for" => array:1 [▼
    0 => "173.XXX.XXX.XXX"
  ]
  "content-length" => array:1 [▶]
  "content-type" => array:1 [▶]
  "php-auth-user" => array:1 [▶]
  "php-auth-pw" => array:1 [▶]
```

These headers aren't case sensitive, right?

**Comment by davzie** [comment]
I have also had this exact same issue but with Laravel 5.3 and Heroku with Heroku SSL.

I had to create a middleware that does this:

```php
<?php
namespace App\Http\Middleware;

use Closure;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\URL;

class ForceSecure
{

    public function handle(Request $request, Closure $next)
    {

        $isSecure = $request->header('x-forwarded-proto') == 'https';
        $isProduction = env('APP_ENV') === 'production';

        if( $isProduction )
        {
            $host = $_SERVER['HTTP_HOST'];
            if (!preg_match('/^www\..*/', $host)) {
                return redirect(env('APP_URL'));
            }
        }

        if (!$isSecure && $isProduction) {
            return redirect(env('APP_URL'));
        }

        if ($isProduction) {
            URL::forceSchema('https');
        }

        return $next($request);
    }
}

```

**Comment by skovmand** [comment]
I have this issue too. Using Elastic Beanstalk on AWS. The Load Balancer forwards the request with these 3 headers:

```
"HTTP_X_FORWARDED_FOR" => "5.186.77.186, 162.158.134.145"
"HTTP_X_FORWARDED_PORT" => "443"
"HTTP_X_FORWARDED_PROTO" => "https"
```

However, Laravel 5.3 still generates links using ```http://```

My `headers` section in `trustedproxy.php` is:

```
    'headers' => [
        Illuminate\Http\Request::HEADER_FORWARDED    => null, // not set on AWS or Heroku
        Illuminate\Http\Request::HEADER_CLIENT_IP    => 'X_FORWARDED_FOR',
        Illuminate\Http\Request::HEADER_CLIENT_HOST  => null, // not set on AWS or Heroku
        Illuminate\Http\Request::HEADER_CLIENT_PROTO => 'X_FORWARDED_PROTO',
        Illuminate\Http\Request::HEADER_CLIENT_PORT  => 'X_FORWARDED_PORT',
    ]
```

**Comment by skovmand** [comment]
Hmm. I must have made a mistake, I think. I solved it by following [this instruction for the Symfony Framework](http://symfony.com/doc/current/request/load_balancer_reverse_proxy.html) and it works fine. 

Since TrustedProxy works the same way, I think the mistake must have been mine..

This is my middleware for trusting the proxy:

```
<?php

namespace App\Http\Middleware;

use Closure;
use Symfony\Component\HttpFoundation\Request;

class TrustLoadBalancer
{
    /**
     * Handle an incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Closure  $next
     * @return mixed
     */
    public function handle($request, Closure $next)
    {
        // This contains the possible ips for our load balancer in AWS.
        $request->setTrustedProxies(['127.0.0.1', '10.0.10.0/24', '10.0.15.0/24']);

        $request->setTrustedHeaderName(Request::HEADER_FORWARDED, null);
        $request->setTrustedHeaderName(Request::HEADER_CLIENT_IP, 'X_FORWARDED_FOR');
        $request->setTrustedHeaderName(Request::HEADER_CLIENT_HOST, null);
        $request->setTrustedHeaderName(Request::HEADER_CLIENT_PROTO, 'X_FORWARDED_PROTO');
        $request->setTrustedHeaderName(Request::HEADER_CLIENT_PORT, 'X_FORWARDED_PORT');

        return $next($request);
    }
}
```

**Comment by fideloper** [comment]
Let me know if anythings unresolved here still!

**Comment by Navisot** [comment]
@fideloper I'm using laravel 5.3 on AWS with an ELB that receives requests on port 443 but sends them to the EC2 instances over port 80. In EC2 NGINX i have:

```
server {
    listen 80;
    server_name example.gr;

    rewrite ^/(.*)$ $scheme://www.$host/$1 permanent;
}

server {
    listen 80;
    server_name www.example.gr;
    index index.php index.html;
    root /var/www/public;
  
   return 301 https://$server_name$request_uri;
  

    if ($host !~* ^(www) {
        rewrite ^/(.*)$ $scheme://www.$host/$1 permanent;
    }
}
```
For TrustedProxy i have:

```
'proxies' => '*'
'headers' => [
        \Illuminate\Http\Request::HEADER_CLIENT_IP    => 'X_FORWARDED_FOR',
        \Illuminate\Http\Request::HEADER_CLIENT_HOST  => null,
        \Illuminate\Http\Request::HEADER_CLIENT_PROTO => 'https',
        \Illuminate\Http\Request::HEADER_CLIENT_PORT  => '443',
    ]

```
The problem is i get too many redirects when i am going to https. Do you have any idea how to solve it? Thanks!
