### ISSUE TITLE
Trying to get real client ip 

### ISSUE THREAD

**Issue by abosami2000** [fideloper/TrustedProxy#60]
Hi 

I'm using laravel behind load balance

and using this package and it works fine with ssl 

but I'm trying to get real ip address for client 

but always it return load balancer server ip.

I use it in Event , so How can get real ip address for client.

thank you very much

**Comment by fideloper** [comment]
The package assumes the load balancer is setting an IP address of the client IP address as `X-Forwarded-For`.

The load balancer should be setting that header with the actual client's IP address. If that's not under your control, chances are it's passing something, it just might not be the exact header `X-Forwarded-For`. In which case, you can adjust the header it searches for within the config file used: https://github.com/fideloper/TrustedProxy/blob/master/config/trustedproxy.php#L57

Note that if you have more than one proxy (perhaps both a CDN and a load balancer), then both proxies need to be forwarding that.
