### ISSUE TITLE
Error: Class 'Fideloper\Proxy\ProxyServiceProvider' not found in Laravel 4.2

### ISSUE THREAD

**Issue by sw-tt-aniruddhbhavsar** [fideloper/TrustedProxy#62]
![screenshot from 2017-03-23 16-46-17 v01](https://cloud.githubusercontent.com/assets/22390681/24245448/ebf78894-0fe8-11e7-8bab-4b22c91e4b65.png)
 I am using laravel 4.2 and used this package and added ServiceProvider and aliases in app/config/app.php but still getting an error as above.  There are no any files like ProxyServiceProvider.php in "/vendor/fideloper/proxy/" directory.

**Comment by fideloper** [comment]
Just to be clear, did you use the [latest v2 tag](https://github.com/fideloper/TrustedProxy/tree/2.1.1) from this package? 

Version `3.0.0+` only works with Laravel 5.1+

**Comment by fideloper** [comment]
Let me know if this is still an issue, and if so, if you grabbed from the v2 tag from the project.
