### ISSUE TITLE
Heroku router IP address

### ISSUE THREAD

**Issue by tillkruss** [fideloper/TrustedProxy#64]
On Heroku, the router sets the `REMOTE_ADDR` to it's own private IP address. Right now the only way for me to trust Cloudflare's proxies, is to overwrite the `REMOTE_ADDR` (set by Heroku) with a Cloudflare IP address.

Is there a better way to solve this using `TrustedProxy`?

```php
if ($request->server->has('HTTP_CF_CONNECTING_IP')) {
    $proxies = preg_split('~\s?,\s?~', $request->server->get('HTTP_X_FORWARDED_FOR'));

    $proxiesAreValid = collect($proxies)
        ->splice(1)
        ->every(function ($ip) {
            return IpUtils::checkIp($ip, $this->trustedProxies);
        });

    if ($proxiesAreValid) {
        $request->server->set('REMOTE_ADDR', $proxies[1]);
    }
}
```

**Comment by fideloper** [comment]
Yep! That's what this should help you with. 
According to [this SO answer](http://stackoverflow.com/questions/18264304/get-clients-real-ip-address-on-heroku), the default settings of the package should work in a Laravel app to get you the real client's IP address. 

> Note: Don't use `$_SERVER['REMOVE_ADDR']` directly, but instead a function on the request object, I think it's just `$request->ip()` in Laravel.

**Comment by fideloper** [comment]
Sorry, if you're using CloudFlare AS WELL as Heroku, you may need to:

1. Trust all proxies ( use `'*'`  for the proxies to trust )
2. You may need to also use `HTTP_CF_CONNECTING_IP` as a header in TrustedProxy's config, however I'm not sure if Heroku will pass that HTTP header on through to your web application. You'l need to dump out `$_SERVER` within Heroku to see.

**Comment by tillkruss** [comment]
I ended up solving it like this: https://gist.github.com/tillkruss/d5fd36d23afd9ddebbb4

**Comment by fideloper** [comment]
Gotcha!
