### ISSUE TITLE
Symfony Request.php setTrustedProxies Requires Two Arguments

### ISSUE THREAD

**Issue by eduardoagarcia** [fideloper/TrustedProxy#68]
I see that the call to `$request->setTrustedProxies()` provides only 1 argument as seen below:

```
private function setTrustedProxyIpAddressesToTheCallingIp($request) {
    $request->setTrustedProxies($request->getClientIps());
}
```
but `setTrustedProxies()` now requires two arguments: https://github.com/symfony/http-foundation/blob/master/Request.php#L587

Unless I am mistaken, TrustedProxy, as is, is no longer working.

**Comment by GrahamCampbell** [comment]
The code you've linked to only takes one argument:

![image](https://cloud.githubusercontent.com/assets/2829600/25862107/c2c497da-34de-11e7-80a0-63aca162c8be.png)

**Comment by GrahamCampbell** [comment]
In Symfony 4.x, the 2nd option will become required.

**Comment by eduardoagarcia** [comment]
@GrahamCampbell yes, but then below that, there is this:

```
if (2 > func_num_args()) {
    // @deprecated code path in 3.3, to be replaced by mandatory argument in 4.0.
    throw new \InvalidArgumentException(sprintf('The %s() method expects a bit field of Request::HEADER_* as second argument. Defining it is required since version 3.3. See http://symfony.com/doc/current/components/http_foundation/trusting_proxies.html for more info.', __METHOD__));
}
```

While it may not be "required" in the parameters, it is definitely throwing an error if it is not provided.

**Comment by GrahamCampbell** [comment]
You are looking at master though, instead of 3.2.x: https://github.com/symfony/http-foundation/blob/3.2/Request.php#L558.

**Comment by Teranode** [comment]
getting this error:
```
production.ERROR: InvalidArgumentException: The Symfony\Component\HttpFoundation\Request::setTrustedProxies() method expects a bit field of Request::HEADER_* as second argument. Defining it is required since version 3.3. See http://symfony.com/doc/current/components/http_foundation/trusting_proxies.html for more info. in /home/animezero/public_html/vendor/symfony/http-foundation/Request.php:593
```

**Comment by GrahamCampbell** [comment]
Hmmm, doesn't seem like Symfony are following their BC promise then. :/

**Comment by Teranode** [comment]
so whats the solution here? cause this gives me errors in routes

**Comment by fideloper** [comment]
Which version of Symfony is being used here when you get the error?

Based on what I see:

1. Symfony 3.2+ should work
2. Symfony 3.3+ (currently in beta) may be broken as it expects 2 parameters
3. Symfony 4 will presumably follow suit with needing 2 parameters

Does that sum this up?

Looks like we can do two things:

1. Let them know that's not a BC change and see if they have feedback on that
2. Send in the 2nd parameter, which PHP will just ignore if it's not used

**The 2nd parameter looks like it just needs the header names we set in the config, right? Would love a 2nd pair of eyes to confirm.** 

E.g.
```php
$request->setTrustedProxies($trustedIps, config('trustedproxy.headers'));
```

**Comment by Teranode** [comment]
Currently using Laravel 5.5.x-dev which calls Symfony 3.4.x-dev

In reply to your "Second Parameter" example, it does work.

**Comment by GrahamCampbell** [comment]
In their upgrading guide for 3.3:

![image](https://cloud.githubusercontent.com/assets/2829600/26400498/092db2ba-4079-11e7-92df-ebae0a77dc32.png)

**Comment by fideloper** [comment]
Please see #70. 

@Teranode if you could, can you please try that PR out in your Laravel 5.5 install to ensure it works?

Thanks!

**Comment by Teranode** [comment]
yes the PR works for me.

**Comment by raulp** [comment]
PR fixes the errors for me, but the laravel route('xxx') helper are generated with HTTP:// for some reason

I had to add $request->server->set('HTTPS', true); in the middleware to get away with it...

Weirdly, the right $_SERVER vars are passed via CloudFlare: https://goo.gl/0U2cKN
And using your config: https://goo.gl/8DQQXC


Any ideas ?

**Comment by raulp** [comment]
the only way i was able to fix this was to return $request::HEADER_X_FORWARDED_ALL in getTrustedHeaderNames(). Of course, had to pass $request to it.

Got a hint from http://symfony.com/blog/fixing-the-trusted-proxies-configuration-for-symfony-3-3

Also, in v.4 for http-foundation , the setTrustedHeaderName will be removed  https://goo.gl/ZViCgZ
Same for all those header constants: https://goo.gl/XeUWzk

I'm still not sure why i can only get it to work with HEADER_X_FORWARDED_ALL ...

**Comment by georgekaratsiolis** [comment]
Is there any fix on that or I have to remove the package?

**Comment by fideloper** [comment]
@raulp can you show a screenshot or example of your code that fixed that for you? I want to be sure I'm clear on that.

I'd like to test that condition out - are you just using Cloudflare or do you have other intermediaries as well (A load balancer?)

**Comment by mhamlet** [comment]
I'm using DigitalOcean's load balancer. This works for me

```php

private function setTrustedProxyIpAddressesToSpecificIps($request, $trustedIps)
    {
        $request->setTrustedProxies((array) $trustedIps, $this->config['trustedproxy.headers']);
    }

    private function setTrustedProxyIpAddressesToTheCallingIp($request) {
        $request->setTrustedProxies($request->getClientIps(), $this->config['trustedproxy.headers']);
    }

    private function setTrustedProxyIpAddressesToAllIps($request)
    {
        // 0.0.0.0/0 is the CIDR for all ipv4 addresses
        // 2000:0:0:0:0:0:0:0/3 is the CIDR for all ipv6 addresses currently
        // allocated http://www.iana.org/assignments/ipv6-unicast-address-assignments/ipv6-unicast-address-assignments.xhtml
        $request->setTrustedProxies(['0.0.0.0/0', '2000:0:0:0:0:0:0:0/3'], $this->config['trustedproxy.headers']);
    }

```

**Comment by fideloper** [comment]
@raulp I believe this should fix your issue now with the latest changes to the PR and its merging.

@mhamlet I'm about to do a release which changes those functions just slightly, please let me know if it breaks after pulling in the next release (to be tagged in a few minutes).

**Comment by mhamlet** [comment]
Yes, it works for me, thank you!

**Comment by fideloper** [comment]
Great!

**Comment by georgekaratsiolis** [comment]
Please let me know if you have a new version, I am using Sucuri as proxy and I want to test it as well.

**Comment by raulp** [comment]
@fideloper thanks, will test tonight

**Comment by fideloper** [comment]
@georgekaratsiolis it's been released, you can update that to get the latest now (tag `3.3.2` on this project)

**Comment by georgekaratsiolis** [comment]
@fideloper  I confirm it works perfectly with Sucuri proxy too. Just upgraded, nothing changed in my code. Thanks
