### ISSUE TITLE
Suggestions when the client IP is missing?

### ISSUE THREAD

**Issue by nicoqh** [fideloper/TrustedProxy#72]
Hi!

Google App Engine doesn't pass the client IP (`$request->getClientIp()` is blank). However, the client IP is present in `X-Forwarded-By` as the first item.

Is there any way we could get the client's IP address using this middleware, or does anyone have any suggestions for doing so?

**Comment by fideloper** [comment]
Can you show an example? Preferably a dump of your $_SERVER global when
that's the case.

**Comment by nicoqh** [comment]
Thanks for replying!

```
[HTTP_X_FORWARDED_FOR] => <client_ip>, <google_proxy>
[REMOTE_ADDR] =>
```

`REMOTE_ADDR` is blank, but the client's IP is available as the first item in `HTTP_X_FORWARDED_FOR`. The proxy's IP doesn't show up any other places than indicated above.

Setting `'proxies' => '*'` would call `setTrustedProxyIpAddressesToTheCallingIp()` and set a blank IP as a trusted proxy, which wouldn't work.

Setting `'proxies' => '**'` would call `setTrustedProxyIpAddressesToAllIps` which will make `isFromTrustedProxy()` return false because the IP (blank) doesn't pass the validation.

**Comment by fideloper** [comment]
Hmmmm, I hate giving this type of answer, but this might be an issue to open up in [Symfony's project](https://github.com/symfony/symfony).

The core Symfony code is testing the trusted proxy based on `REMOTE_ADDR` only in two places:

1. [first place](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpFoundation/Request.php#L857)
2. [second place](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpFoundation/Request.php#L2009)

If that is empty, I don't think I can get around that limitation with my package here! In fact, Symfony itself may  not be able to get around that, I'm not really sure. That being empty feels like a bug in their implementation, although I suppose its possible they have security reasons for that.

**Comment by nicoqh** [comment]
Yes, it's a bit tricky that `REMOTE_ADDR` is empty.

Creating my own middleware which populates the server global might be the best (and only) solution. That way I can keep using the conventional helper methods (`$request->ip()`)

I appreciate the detailed response! Thanks a lot.

I'll also close this issue because there's nothing more you can do :)

**Comment by rduque1** [comment]
Hi, I had the same issue and it didn't work if I put

```$_SERVER['REMOTE_ADDR'] = $_SERVER['HTTP_X_FORWARDED_FOR'];``` 

in an middleware that was called before the TrustedProxy. I had to put in the middleware 

`$request->server->set('REMOTE_ADDR', $ip);`. 

I am just adding it in case some else faces this issue.

**Comment by rixgov** [comment]
@rduque1 Where exactly did you implement this fix, I can't figure out which file you are referring to.  I'm having the same problem where I keep getting my Forge provisioned load balancer IP and can't seem to figure out how to get my actual client IP.  It's driving me nuts!

**Comment by rduque1** [comment]
@rixgov I created an middleware:

```php
<?php

namespace App\Http\Middleware;

use Closure;
use Config;
// use Illuminate\Support\Facades\Log;

class GaeRemoteAddressFix
{
    /**
     * Handle an incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Closure  $next
     * @return mixed
     * @link https://github.com/fideloper/TrustedProxy/issues/72
     */
    public function handle($request, Closure $next)
    {
        $isGoogleAppEngine = Config::get('trustedproxy.hosting.googleAppEngine') ? true : false;
        if( $isGoogleAppEngine && empty($_SERVER['REMOTE_ADDR']) && isset($_SERVER['HTTP_X_FORWARDED_FOR']) ) {
            $ips = explode(',', $_SERVER['HTTP_X_FORWARDED_FOR'] );
            $_SERVER['REMOTE_ADDR'] = $ips[0] ;
            $request->server->set('REMOTE_ADDR', $ips[0]);
        }
        return $next($request);
    }
}
```


In the `app/Http/Kernel.php` I registered this middleware before the TrustedProxy:

```php
    /**
     * The application's global HTTP middleware stack.
     *
     * These middleware are run during every request to your application.
     *
     * @var array
     */
    protected $middleware = [
        \Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode::class,
        \Bepsvpt\SecureHeaders\SecureHeadersMiddleware::class,
        \App\Http\Middleware\GaeRemoteAddressFix::class,
        'Fideloper\Proxy\TrustProxies'
    ];
```

In the middleware I use a config value `'trustedproxy.hosting.googleAppEngine'`, this is just a variable I defined in the config if an ENV variable specific to GAE is set.

I hope it helps

**Comment by fideloper** [comment]
One other thing I've done is used `map` in Nginx to add fastcgi_parameters to the PHP response (which get populated in $_SERVER). This can potentially be used to populate `REMOTE_ADDR` when it's empty in Nginx so you don't need to have it in-code.

More details here if you're interested: https://serversforhackers.com/c/nginx-mapping-headers

**Comment by rixgov** [comment]
Thanks for all the help guys! This seems to be such a common problem, I’m surprised there isn’t an easy solution, or a package that handles load balancing and pass through.  If I can get either of those solutions to work, I’ll try creating a package (if that’s even possible for this kind of issue).
