### ISSUE TITLE
Non-Numeric Value encountered

### ISSUE THREAD

**Issue by kapsoft** [fideloper/TrustedProxy#74]
I had been up and running with you proxy for about a month now on an AWS box with load balancer and Laravel on backend. After an upgrade (at 3.3 now) now getting an error:

```
ErrorException in TrustProxies.php line 159:
A non-numeric value encountered
in TrustProxies.php line 159
at HandleExceptions->handleError('2', 'A non-numeric value encountered', '/home/forge/isdb.io/code/Laravel/vendor/fideloper/proxy/src/TrustProxies.php', '159', array('set' => '0', 'key' => 'forwarded')) in /home/forge/isdb.io/code/Laravel/vendor/fideloper/proxy/src/TrustProxies.php line 159
at TrustProxies->Fideloper\Proxy\{closure}('0', 'forwarded')
```

Scratching my head with no clue whats happening....any help would be appreciated.

Thx

DJK

**Comment by fideloper** [comment]
There's here: https://github.com/fideloper/TrustedProxy/blob/master/src/TrustProxies.php#L159

It's doing bitwise math on values which apparently are non-numeric.

Can you let me know what version of Laravel and Symfony are being used? (`composer.lock` may have information on the actual versions installed for `laravel/framework` and `symfony/http-kernel`.

**Comment by kapsoft** [comment]
"name": "laravel/framework",
            "version": "v5.3.31",
not sure if this is correct Symfony entry but:
"name": "symfony/http-kernel",
            "version": "v3.1.10",

I did notice the config file probably got overwritten since that ip address for proxie should have been '*' I believe.....but changing that did not make error go away.

**Comment by zakkyzebra** [comment]
We are receiving the same error on our local dev machine, but it seems to be okay on our AWS instance behind the load balancer. Here is our json.lock:

"name": "fideloper/proxy",
"version": "3.3.2",

"name": "laravel/framework",
"version": "v5.3.31",

**Comment by fideloper** [comment]
Interesting! Can you show me the laravel and symfony version as well?

**Comment by kapsoft** [comment]
Since my site is down I had to "do" something. So I upgraded to latest Laravel 5.4. Fine on devel machine but on AWS getting new error:

The Symfony\Component\HttpFoundation\Request::setTrustedProxies() method expects a bit field of Request::HEADER_* as second argument. Defining it is required since version 3.3. See http://symfony.com/doc/current/components/http_foundation/trusting_proxies.html for more info.

InvalidArgument exception.

Thoughts?

DJK

**Comment by fideloper** [comment]
That's the error receoved the setTrustedProxies has no 2nd argument. That
shouldn't be the case in version 3.3.2 of this package - did this package
get updated as well?

**Comment by kapsoft** [comment]
Chris,

Turns out I had some middleware in there that forces https. Not in your code.

Interesting (slight off topic but you might know why this is occurring). What was working before now gets "too many redirects". My code:

public function handle($request, Closure $next)
    {
        if (!app()->environment('local')) {
            // for Proxies
            Request::setTrustedProxies([$request->getClientIp()], $this->getTrustedHeaderSet());

            if (!$request->isSecure()) {
                return redirect()->secure($request->getRequestUri());
            }
        }

        return $next($request);
    }

Thanks for the help.

DJK

**Comment by jbrooksuk** [comment]
I'm getting this error too after upgrading to 3.3.2.

- Laravel v5.3.31
- PHP 7.1

**Comment by tai1030** [comment]
Same here.
- Laravel 5.3.31
- PHP 7.1

I downgraded to 3.3.1 from 3.3.2, it is fine.

**Comment by livingos** [comment]
Me too.

- Laravel 5.1
- PHP 7.1

3.3.1 is ok.

**Comment by fideloper** [comment]
Release 3.3.3 created to resolve this, let me know if you run into any issues!

https://github.com/fideloper/TrustedProxy/releases/tag/3.3.3
