### ISSUE TITLE
Can I use this to add a folder prefix when proxying?

### ISSUE THREAD

**Issue by gcleaves** [fideloper/TrustedProxy#85]
Hi. My goal is to have the Nginx reverse proxy address https://my.company.name/laravel redirect to my Laravel instance sitting at http://my.local.ip/ . Other projects have a `web_root` setting that allows this to be done easily. Would this package help me achieve that? Right now the folder name "laravel" is causing the problem. I need a folder prefixed to everything: routes and assets.

Thanks for listening.

**Comment by fideloper** [comment]
Nope, this package is about  making Laravel aware that your application is
behind a proxy, such as a load balancer. It doesn't provide any proxy
functionality.
