### ISSUE TITLE
[Feature Request] Add support for setTrustedHosts

### ISSUE THREAD

**Issue by ejunker** [fideloper/TrustedProxy#86]
In Symfony's Request class it says:
> to avoid host header injection attacks, you should provide a list of trusted host patterns

Add a way to specify an array of trusted host patterns. The code would then need to call `$request->setTrustedHosts($hostPatterns)`

**Comment by fideloper** [comment]
Hi!
Can you give me an example - is that just using CIDR notation such as `10.0.0.0/8`?

**Comment by ejunker** [comment]
I ran a security scanner against by app and it was setting custom `Host:` headers and was able to manipulate the base URL of my app somehow. I added code similar to the following:

```
$request->setTrustedHosts(['localhost', '.*\.?mydomain.com$']);
```

Then if an attacker sent a header like `Host: attacker.com` it would not be used since it is not in the whitelist of trusted hosts.

If you are using apache's name based virtual hosting I don't think this would be an issue but in my case I have the app as the default virtual host so I think all web requests get routed to it regardless of the Host header.

**Comment by fideloper** [comment]
That’s not really specific to this package tho, Host headers can be set by
any client - nginx and Apache both use the host header to match to a server
config and have defaults to fall back to if no host is is found.

Trusted proxy does help if you’re able to know the trusted proxy’s IP, as
you’ll have a better idea if the host header should be trusted as well.

**Comment by ejunker** [comment]
I see how `setTrustedHosts` may not belong in this package. Closing issue.
