### ISSUE TITLE
AWS EBS and Lumen 5.4 - LB IP

### ISSUE THREAD

**Issue by andrew-s** [fideloper/TrustedProxy#87]
Hi,

I'm using Elastic Beanstalk (with a load balancer) and Lumen 5.4 - I followed the steps (code included below) however, when calling `$request->getClientIp();` I'm still getting the load balancer's IP;

`bootstrap/app.php`

```php
 $app->middleware([
     // other middleware
     'Fideloper\Proxy\TrustProxies'
 ]);

// other service providers
$app->register(Fideloper\Proxy\TrustedProxyServiceProvider::class);
```

`config/trustedproxy.php`

```php
<?php

return [
    'proxies' => [
        '*',
    ],

    // These are defaults already set in the config:
    'headers' => [
        (defined('Illuminate\Http\Request::HEADER_FORWARDED') ? Illuminate\Http\Request::HEADER_FORWARDED : 'forwarded') => null,
        \Illuminate\Http\Request::HEADER_CLIENT_IP    => 'X_FORWARDED_FOR',
        \Illuminate\Http\Request::HEADER_CLIENT_HOST  => null,
        \Illuminate\Http\Request::HEADER_CLIENT_PROTO => 'X_FORWARDED_PROTO',
        \Illuminate\Http\Request::HEADER_CLIENT_PORT  => 'X_FORWARDED_PORT',
    ]
];
```
What's actually being forwarded;

```php
[HTTP_X_FORWARDED_FOR] => 141.105.x.x (real IP)
[HTTP_X_FORWARDED_PORT] => 80
[HTTP_X_FORWARDED_PROTO] => http
```
Am I missing something from this configuration?

**Comment by fideloper** [comment]
Sounds like you are seeing the HTTP_X+_FORWARDED headers are there - the first thing I'd try is t use a double star instead of single one for which proxy to trust -

```php
<?php

return [
    'proxies' => [
        '**',
    ],

    // These are defaults already set in the config:
    'headers' => [
        (defined('Illuminate\Http\Request::HEADER_FORWARDED') ? Illuminate\Http\Request::HEADER_FORWARDED : 'forwarded') => null,
        \Illuminate\Http\Request::HEADER_CLIENT_IP    => 'X_FORWARDED_FOR',
        \Illuminate\Http\Request::HEADER_CLIENT_HOST  => null,
        \Illuminate\Http\Request::HEADER_CLIENT_PROTO => 'X_FORWARDED_PROTO',
        \Illuminate\Http\Request::HEADER_CLIENT_PORT  => 'X_FORWARDED_PORT',
    ]
];
```

**Comment by andrew-s** [comment]
Even when using two stars, I seem to still be retrieving some internal proxy. Is there anything I can output to make this easier to debug?

**Comment by fideloper** [comment]
There is a test branch (`feature/debugger`) that includes a debugging screen - you pull it in with composer.

Then there’s a route you can add to your web.php rites file to enable the `/trusted-proxy` route which has some debugging info:

```php
# file: routes/web.php

Fideloper\Proxy\Proxy::auth(function($request) {
    // return auth()->user()->mail == 'someadmin@example.com';
    return true; // Returning true will enable the /trusted-proxy route
});

```

**Comment by fideloper** [comment]
This might be something to keep your eye on as well: https://github.com/fideloper/TrustedProxy/issues/88

**Comment by fideloper** [comment]
Hey - did you get that debugger working?

**Comment by andrew-s** [comment]
I've been trying to get this integrated - how well does this debugger work with Lumen?

Keep getting; 

{code}
Call to undefined function Fideloper\\Proxy\\request()
{code}

Also, that $request variable won't exist in the bootstrap/app. Am I missing something with this?

**Comment by fideloper** [comment]
Not sure, I haven't tested with Lumen yet!

`$request` is an argument parameter passed to the closure when it's called within the `Fideloper\Proxy\Proxy::auth()` method. It's not something that would exist within the scope of the route file.

Lumen may not have the global `request()` helper method which it used in [Fideloper\Proxy\Proxy](https://github.com/fideloper/TrustedProxy/blob/feature/debugger/src/Proxy.php#L39). I think that'll need to get replaced with `app(Illuminate\Http\Request::class)`.

```php

     * Set the callback that should be used to authenticate Proxy users.
     *
     * @param  \Closure  $callback
     * @return static
     */
    public static function auth(Closure $callback)
    {
        static::$authUsing = $callback;
        $registerRoutes = static::check(
            app(Illuminate\Http\Request::class)
        );
        if( $registerRoutes )
        {
            static::routes();
        }
        return new static;
    }
```

**Comment by andrew-s** [comment]
I had to make a few changes to get this to work under Lumen, if you want a copy of my code - let me know, I don't want to PR it as it likely breaks Laravel now.

Anyway, showed some interesting things - now that I finally had reports, adjusted the "proxies" in the config to some different things, then relooked at #88 - swapped it to `0.0.0.0/0` and now it reports the correct IP. 

I should probably have started with putting that into the config however, is this a permanent solution?

**Comment by fideloper** [comment]
I'd love to know what you needed to change for Lumen (in case I missed something). See my update on #88 as well. In theory, using `**` is setting that exact ipv4 IP address, but if you get errors, let me know.

**Comment by andrew-s** [comment]
Added a pull request so you can see the changes. `*` and `**` return the LB IP, `0.0.0.0/0` returns the user's IP from the LB headers.

**Comment by fideloper** [comment]
Closing this to clean up, keeping the PR open.
