### ISSUE TITLE
Outdated documentation

### ISSUE THREAD

**Issue by webmake** [fideloper/TrustedProxy#88]
As you refer in readme `'*'` for broadcast or `'**'` is not compatible with http foundation, see https://github.com/symfony/symfony/issues/24424
Current valid solution would be only '0.0.0.0/0'

**Comment by fideloper** [comment]
Thanks - I'll keep an eye on that!

**Comment by fideloper** [comment]
Sorry I wasn't really clear here - the use of `*` and/or `**` is specific to this package, not Symfony.

The use of two stars `**` set the following:

```php
$request->setTrustedProxies(['0.0.0.0/0', '2000:0:0:0:0:0:0:0/3'], $this->getTrustedHeaderSet());
```

...which is what you're setting as a valid solution (this also includes an equivalent ipv6 address as well).

(See here for that code: https://github.com/fideloper/TrustedProxy/blob/master/src/TrustProxies.php#L121 )

Can you double check that using `**` doesn't work for you? If so I'll need to know if you get any errors or what behavior constitutes "not working" in your case so I can try to recreate it.

**Comment by fideloper** [comment]
Closing to clean this up, will keep the PR open and decide what to do with it.
