### ISSUE TITLE
Documentation suggestion: haproxy

### ISSUE THREAD

**Issue by dsadinoff** [fideloper/TrustedProxy#9]
For proxies such as haproxy, I would suggest that we mention the following snippet in the docs:

```php
/* fixup the request proxy interpreter for haproxy */
   Request::setTrustedHeaderName(Symfony\Component\HttpFoundation\Request::HEADER_CLIENT_PROTO,'X_FORWARDED_SCHEME');
```

**Comment by fideloper** [comment]
Marking as duplicate to #7, as the solution is the same. I'm hoping to add that as a configuration available (and documenting it).

Thanks!
