### ISSUE TITLE
Outdated documentation?

### ISSUE THREAD

**Issue by JohnnyWalkerDesign** [fideloper/TrustedProxy#95]
According to the documentation I'm supposed to register the HTTP Middleware in file `app/Http/Kernel.php`:

`'Fideloper\Proxy\TrustProxies',`

Except in Laravel 5.5 this already appears to exist:

`\App\Http\Middleware\TrustProxies::class,`

With the above referenced file having the following reference:

`use Fideloper\Proxy\TrustProxies as Middleware;`

What's more it also contains header mapping information:

`Request::HEADER_FORWARDED => 'FORWARDED',`
`Request::HEADER_X_FORWARDED_FOR => 'X_FORWARDED_FOR',`
`Request::HEADER_X_FORWARDED_HOST => 'X_FORWARDED_HOST',`
`Request::HEADER_X_FORWARDED_PORT => 'X_FORWARDED_PORT',`
`Request::HEADER_X_FORWARDED_PROTO => 'X_FORWARDED_PROTO',`

And the created `config/trustedproxy.php` has warnings in it (eg. Constant HEADER_CLIENT_IP is deprecated).

Is the documentation outdated?

**Comment by fideloper** [comment]
Hi!

Laravel 5.5 has it's own implementation that's a bit different from this packages (note that the package is not laravel 5.5 specific). The package existed first with it's own docs, and then Laravel added it to core with it's own way to use it.

That being said, I'll update the docs to make that more clear, as more and more people will be using Laravel 5.5. That should definitely be more clear within this repository!


As for "undoing the damage" I believe the only things you have to worry about are deleting `config/trustedproxies.php` if it exists, and then deleting the line registering the `Fideloper\Proxy\TrustProxies` middleware (and keep `\App\Http\Middleware\TrustProxies::class` registered as a middleware).


The warnings are thanks to Symfony doing some updates to depreciate certain settings. If you go back to Laravel's implementation, I believe they'll go away.
